### ISSUE TITLE
getAllChildren

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tilebelt#26]
I need to invalidate a tile and get all the children below it that need to be regenerated.

I'm thinking something like this:
- `tilebelt.getAllChildren(tile, maxZoom)`
- `tilebelt.getAllChildren([18, 24, 6], 14)`

**Comment by morganherlocker** [comment]
I think this would do the same thing as this proposal: https://github.com/mapbox/tilebelt/issues/19

**Comment by aaronlidman** [comment]
I believe the idea behind `tilesToZoom` was to get the final zoom level of all the children, not the entire pyramid. I started trying to adapt `tilesToZoom` to do this but found it depends on turf, so I'm trying a different approach. I think we can get a working `tilesToZoom` out of that as well.

If I don't lose my mind in recursion that is.

**Comment by morganherlocker** [comment]
> was to get the final zoom level of all the children, not the entire pyramid

**Comment by aaronlidman** [comment]
```js
var tilebelt = require('tilebelt');

function getAllChildren(tile, maxZoom, sort) {
    if (tile[2] >= maxZoom) return [tile];
    var zoomDiff = maxZoom - tile[2];
    var allChildren = [];
    theChildren(tile);
    return allChildren;

    function theChildren(tile) {
        var children = tilebelt.getChildren(tile);
        allChildren = allChildren.concat(children);
        if (children[0][2] === maxZoom) return;
        children.forEach(theChildren);
    }
}

console.log(getAllChildren([18,24,6], 14));
```

Here's what I did, it works and I'm using it in a project but it's probably not performant enough to include in tilebelt.
