### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by DenisCarriere** [mapbox/tilebelt#33]
No immediate timeline for this, but could a new release be published for `tilebelt`.

The resolved [Tile X Wrapping issue](https://github.com/mapbox/tilebelt/pull/32) trickles down to fix many other dependent libraries (including [`@mapbox/tile-cover`](https://github.com/mapbox/tile-cover))

CC: @morganherlocker

**Comment by mourner** [comment]
I'm so sorry! Published as https://github.com/mapbox/tilebelt/releases/tag/v1.0.2
