### ISSUE TITLE
Incorrect output for bboxToTile crossing Lng -90.

### ISSUE THREAD

**Issue by sharkinsspatial** [mapbox/tilebelt#36]
The following 
```
const bbox = [-91, 32, -89, 34];
const tile = tilebelt.bboxToTile(bbox);
```
Returns tile `[ 0, 0, 1 ]`

Internally `getBboxZoom` is incorrectly returning 1 for this bbox.  I believe this is related to the discussion here https://github.com/mapbox/tilebelt/issues/8 but my understanding of the bit masking operations at https://github.com/mapbox/tilebelt/blob/master/index.js#L250 are limited.

**Comment by wolfiex** [comment]
Any notes on the solution?
